### ISSUE TITLE
Theme isn't loading [Bug]

### ISSUE THREAD

**Issue by Luna-devv** [ccrashtek/simple-pink-discord#1]
**Heyia,**
I tried to use this theme but nothing happens when I enable it. Even if I restart my discord.
[screenshot](https://cdn.xyna.space/1637174205.png)
<br><br><br>

## Some informations if you need

| SYSTEM / DISCORD |   | 
|---|---|
| Locale  | en-US  | 
|  OS |  Windows 64-bit | 
|  Architecture | x64 |
| Release Channel | canary  | 
|  App Version |  1.0.42 | 
|  Build Number | 105125  |
|  Build ID | 68e9be02a542b7ffcbbcfd6c6c53de065f4ac722 |

| PROCESS VERSIONS |   | 
|---|---|
| React | 17.0.2  | 
|  Electron |  13.4.0 | 
|  Chrome | 91.0.4472.164 |
| Node | 14.16.0 | 

| POWERCORD  |   | 
|---|---|
| Commands | 12 | 
|  Settings | 16 | 
|  Plugins | 19 / 20 |
| Themes  | 3 / 8 | 
|  Labs | 0 / 4 | 
|  Settings Sync | false |
|  Cached Files | 221 |
|  Account | false |
|  APIs | 9  |

| GIT |   | 
|---|---|
| Upstream | Official | 
|  Revision | [[1d2318b]](https://github.com/powercord-org/powercord/commit/1d2318bcd7c5e5a5230d8bf25813ed648cfd7b76) | 
|  Branch | v2 |
| Latest | true |

**Comment by ccrashtek** [comment]
I simply forgot to change _**"theme"**_ variable in _**powercord_manifest.json**_ file, change _**cpd.css**_ to _**spd.css**_ or re-download theme.

**Comment by ccrashtek** [comment]
о челик то русский оказывается лол
